version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306

  redis:
    image: redis:5
    environment:
      - REDIS_PASSWORD:${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
